language: cpp

before_script:
# Building & installing gtest:
- CHECKOUT_DIR=$(pwd)
- GTEST_DIR=${CHECKOUT_DIR}/3rdparty/gtest
- git clone https://github.com/google/googletest.git ${GTEST_DIR}/sources
- mkdir ${GTEST_DIR}/build
- cd ${GTEST_DIR}/build
- cmake ${GTEST_DIR}/sources -DCMAKE_INSTALL_PREFIX=${GTEST_DIR}/install
- cmake --build .
- cmake --build . --target install

script:
- mkdir ${CHECKOUT_DIR}/build
- cd ${CHECKOUT_DIR}/build
- cmake ${CHECKOUT_DIR}/source -Dwith-tests=ON -DGTEST_ROOT=${GTEST_DIR}/install
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T matrix-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uziminas1990:$BINTRAY_API_KEY "https://api.bintray.com/content/ziminas1990/otus-cpp/homework-06/1.0.$TRAVIS_BUILD_NUMBER/matrix-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    on:
      branch: homework-06
